<div class="head">
    <a href="http://www.lpsystems.eu/" target="_blank"><img src="/logo.png" alt="ETH Relay" title="ETH Relay"/></a>
</div>

<div id="title">
    <span id="modelName">ETHRELAY</span>
    <div class="right">Status:&nbsp;<span id="status"></span></div>
</div>

<div class="head">
    <div id="menu">
	<a href="/index.htm">Home</a>
	<a href="/prt/index.htm">Authentication</a>
	<a href="/prt/local.htm">Local LAN</a>
	<a href="/prt/io.htm">IO</a>
	<a href="/prt/relay.htm">Relay</a>
	<a href="/prt/analog.htm">Analog</a>
	<a href="/prt/date.htm">Date &amp; Time</a>
	<a href="/about.htm">About</a>
    </div>
</div>